name: docker.nestjs

on:
  schedule:
    # 毎週月曜日の0時(JST)に実行
    - cron: "0 15 * * 0"
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker-nestjs.yml
      - nestjs/**

env:
  # Format
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository }}
  IMAGE: nestjs

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    defaults:
      run:
        working-directory: nestjs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download release tool
        run: |
          wget -q https://github.com/ms-naughty-ghost/release-tool/releases/download/1.0.0/release-tool.zip -O release-tool.zip
          unzip release-tool.zip

      - name: Extract Docker tag from release-tool
        id: meta
        run: echo "tag=ghcr.io/$REPOSITORY-$IMAGE:$(./release-tool | tr -d '\n')" >> $GITHUB_OUTPUT
      
      - name: Extract Docker description from release-tool
        id: description
        run: echo "description="$(./release-tool -r $(./release-tool | tr -d '\n'))"" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ steps.meta.outputs.tag }} \
            --label "org.opencontainers.image.description=${{ steps.description.outputs.description}}" \
            --push .
